### ISSUE TITLE
Initial Economy

### ISSUE THREAD

**Issue by HJPearce** [UQdeco2800/2022-studio-3#139]
# **Description**
Adds ways for the user to spend their collected resources on buildings and units; this includes building upgrades, the placement of new buildings and the construction of units in barracks / whichever building they may be built in.

## SubFeature/component (optional)
 - Proper menus for building and unit construction (being able to choose what to build)
 - Expenditure of collected resources
 - The ability to choose where to place buildings (i.e. a highlight for placement selection w/ ability to cancel)
 - Proper connections of walls (i.e walls can be placed grid aligned with other walls, can be placed as a line with cost per tile and potentially cannot be placed such that the centre cannot be reached by enemies)
 - Cooldowns on the production of units and buildings
 - Managing where units are placed on construction
 - Affordance for removing non-essential buildings (walls, Barracks and camp) in case of misplacement or general dislike
 - Leveling up buildings and resources 

## **Examples (optional)**
- **Wall construction**: From the building menu (either attached to a worker or globally), you select to build a wall. This brings up a highlight of where the wall would be built, which you can use to place a starting point for the wall. From there moving your mouse along the axes of the game tiles creates a highlight of connected wall segments with the appropriate cost. If there are obstructions in the path of the wall or you cannot afford to build a wall over a certain length, the highlight will turn red and you will not be able to complete construction. Once a suitable location & wall length has been selected, the user may click again to finish construction.
- **Unit construction**: By selecting a building with associated units (e.g. workers and spearmen for the main hall, other units from the Barracks), a menu for constructing units is brought up. If sufficient resources are in the stockpile, when a unit is selected it will be produced near the initially selected building.
# **Dependencies**

Building construction relies on both the existence of buildings and selection (both of which were implemented in the previous sprint)  
Cooldown format needs to be shared with god power team (link ticket when made)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #140
- [x] #141
- [x] #142
- [x] #143
- [ ] #160

**Completion Deadline:** Oct. 12

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by nhVietS** [comment]
Finished this feature (at some level)
