### ISSUE TITLE
Spawning menu creation continuation

### ISSUE THREAD

**Issue by Harqua** [UQdeco2800/2022-studio-3#215]
# **Description**
**Task:** [Spawning menu creation](#140).

This task ticket is the continuation of the previous task ticket (see #140) as there were some issues with the code during sprint 3. The main goal of this task has switched to getting the building to spawn the soldier units on the map (and possibly the worker as well) in order to get the game playable by the end of the sprint.

# **Dependencies**

Icon Assets are retrieved from the icons of each unit that Team 1 has created.
Menu Widget has been completed in the previous sprint and will be used.

# **Milestones**
Remaining steps that need to be completed for this task.
- [x] Unit menus need to be attached to whether the appropriate building is selected (taken over by team 6. See #233 )
- [x] Global building menu needs to call appropriate placement selection process

# **Documentation**
-  [In-Game Menu](https://github.com/UQdeco2800/2022-studio-3/wiki/In-game-Menu)
 
# **Member**
- Garryco Thandi (@Harqua)
- Hoang Viet Nguyen (@nhVietS)

**Comment by Harqua** [comment]
The code for menu for the units has been pushed to the main, but the button to make it appear were commented as team 6 is taking over

**Comment by nhVietS** [comment]
I have finished the first version of the menu, could you guys have a quick look and I appreciate your feedbacks.
Here a list of questions that I want to here from u guys:
- On a scale of 1 – 5, how effective and ‘easy to use’ was the menu system for building (with 1 being ‘terrible’ and 5 being ‘great’)
- On a scale of 1 – 5, how likely are you to want to use this version of the menu in this game (with 1 being ‘definitely not’ and 5 being ‘yes, absolutely’
- Describe the feelings you experienced while playing the game?
- What did you enjoy about the building process?
- What aspects of the menu could be improved?

**Comment by nhVietS** [comment]
Some quick informations that may useful when you review it: 
- The menu currently works fine for the first time you spawn it, but not the second and later
- I try to hide the menu after u choose the building button but it still not implemented well yet

**Comment by Harqua** [comment]
Participant 1:
1) 4
2) 5
3) "I think it is intuitive enough and simple to use"
4) "I like the freedom of choosing a specific location to build the buildings"
5) "Other than the bug mentioned, I would like the image of the buildings being pressable instead of the cost button"

**Comment by Harqua** [comment]
Participant 2:
1)  3
2) 3
3) "I would say it is very common for RTS games, other than the bug that kinda disturbs the gameplay"
4) "I like how the placement of the button where it is very obvious and easy to find"
5) "Maybe make the button position a little bit left so it won't trigger the camera movement"

**Comment by quocdat402** [comment]
1. 4
2. 3
3. The menu is simple to use, however there are some bugs that in the menu that cause you cannot spawn a second unit.
4. The design is good and buttons are easy to navigate.
5. Add a close button in the menu to make it easier to close the menu, make the menu disappear when you already choose the unit to place it on the map.

**Comment by yobicakes** [comment]
1. 4
2. 5
3. The new design is intuitive, pleasant to use and all around, very simple. 
4. I like how the user can get specific with the building placement. In general, navigation is very simple.
5. Other that the bug, consider a collapsible that prevents clutter in the screen.

**Comment by yolandawsirait** [comment]
Participant 5:
1) 4
2) 3
3) "The menu is still a little buggy. However, it is easy to navigate and learn."
4) "It is easy to use, you just have to click it and place the building in the game."
5) "Make a cooldown option"

**Comment by yolandawsirait** [comment]
Participant 6:
1) 3
2) 5
3) "Simple, intuitive and easy to use. The design of the menu is also great"
4) "Building placement is flexible, giving players freedom to place it in he most strategic place."
5) "Fixing the creation of the buildings"

**Comment by yolandawsirait** [comment]
Participant 7:
1) 5
2) 5
3) "The menu is informative to new users, giving the pictures, cost and description of the buildings."
4) "I can easily use it without further instructions"
5) "Placements of the attributes could be better. Also, make the menu easily closeable."
