### ISSUE TITLE
Team 9 Sprint 4 - Finalising In-Game Menu

### ISSUE THREAD

**Issue by Harqua** [UQdeco2800/2022-studio-3#227]
# **Description**
This feature ticket is a continuation of #139 to finish up tasks that need to be completed by the end of sprint 4. The aim of this ticket is to make the game at least playable in terms of creating menus to allow users to choose which building to build and which troops to deploy.

# **Dependencies**

Might need the soldier units to work properly.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #214
- [x] #215 

**Completion Deadline:** Oct. 17

# **Documentation**
- (In-Game Menu)[https://github.com/UQdeco2800/2022-studio-3/wiki/In-game-Menu]

# **Members**
- Hayden Pearce (@HJPearce)
- Garryco Thandi (@Harqua)
- Hoang Viet Nguyen(@nhVietS)
- Mehr (@Mehr-creates)
- Yolanda (@yolandawsirait)

**Comment by nhVietS** [comment]
Finished all described tasks.
