### ISSUE TITLE
create a Music class

### ISSUE THREAD

**Issue by Xanadu-james** [UQdeco2800/2022-studio-3#46]
# **Description**
**Task:** [create a music class].
**Feature:** [Sound and Background Music](#11)

Create a music class that includes functions for other teams to use(e.g. to play the specific sound effect they want)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] prototyping the structure and documenting on wiki(Aug. 27)
- [ ] complete the class definition (Aug. 29)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Xinrui Tan (@Xanadu-james) (Xinrui Tan)

**Comment by nhVietS** [comment]
Close due to teammate drop the course.
