### ISSUE TITLE
Team 1:  Responsive Sizing BUG

### ISSUE THREAD

**Issue by Akshath-K** [UQdeco2800/2022-studio-3#68]
## Description
While implementing our Unit selection/detection feature which displays an information box for the units (in this case displaying HP or hearts).  The interface does not respond to different resolution in full-screen mode, the UI gets skewed which can be later seen in the screenshots section below.  However, running the game in any supported resolution in windowed mode displays it correctly. 

## How To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Main Menu' or click Pause if you are already inside the game. 
2. Click on 'Settings'
3. Tick/uncheck the  'Full-screen box'
4. Click on apply for these new settings to take place.
5. See error

## Expected Behaviour
The hearts for the corresponding selected units must be shown inside of the information box and not outside it. It should not be being displayed at any random space on the screen. 

## Screenshots
This screen shots shows the game running in **windowed mode.**  The hearts being displayed of the selected units within the designated space in the information box.  It is dynamically changed depending on how many units are selected. Each heart directly corresponds to a selected unit. 

![image](https://user-images.githubusercontent.com/110160158/187114374-3f9edf68-f2e2-4d69-a16e-a2bcc0aca237.png)

The same cannot be said when using the game on **full-screen mode.** The same amount of units selected but the hearts are not displayed in its designated space inside the information box. 

![image](https://user-images.githubusercontent.com/110160158/187113777-124bdf96-3671-4e01-9581-cb0accc19c9d.png)

## Additional Context
The feature was implemented in the game while working on windowed mode.

## Temporary Fix
Open the game and set it to _any supported resolution in windowed mode_ and _not full-screen._

**Comment by Sourav-RC** [comment]
Fixed
